### ISSUE TITLE
Despite Insufficient Funds transaction can be broadcast

### ISSUE THREAD

**Issue by aggroed** [MattyIce/steem-engine#8]
Balance is too low, ERROR MESSAGE should be displayed

![image](https://user-images.githubusercontent.com/28451542/52662984-9425e780-2ed3-11e9-8a49-902e735088c6.png)

System allows to broadcast transaction and it's registered.

![image](https://user-images.githubusercontent.com/28451542/52662996-99833200-2ed3-11e9-9581-89ccba07a986.png)

**Comment by asgarth** [comment]
Included in the next PR.
